name: "CI"
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  tests:
    strategy:
      matrix:
        system: [ "x86_64-linux", "aarch64-linux"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v2
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          accept-flake-config = true
          extra-platforms = aarch64-linux
    - uses: cachix/cachix-action@v14
      with:
        name: entropia
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - run: nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --flake .#checks.${{ matrix.system }}
