name: "CI"
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  linux:
    strategy:
      matrix:
        system: [ "x86_64-linux", "aarch64-linux"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          accept-flake-config = true
          extra-platforms = aarch64-linux
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with: 
        use-flakehub: false
    - uses: cachix/cachix-action@v15
      with:
        name: entropia
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
        useDaemon: false
    - run: nix run .#nix-fast-build -- --skip-cached --no-nom --flake .#checks.${{ matrix.system }}

  # disabled for now, as nix-fast-build failes on macos 
  # macos:
  #   strategy:
  #     matrix:
  #       os: [ "macos-13", "macos-14" ]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: DeterminateSystems/nix-installer-action@main
  #     with:
  #       extra-conf: |
  #         accept-flake-config = true
  #   - uses: DeterminateSystems/magic-nix-cache-action@main
  #     with: 
  #       use-flakehub: false
  #   - uses: cachix/cachix-action@v14
  #     with:
  #       name: entropia
  #       authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  #       extraPullNames: nix-community
  #       useDaemon: false
  #   - run: nix run .#nix-fast-build -- --skip-cached --no-nom --flake .#checks.${{ matrix.os == 'macos-14' && 'aarch64-darwin' || 'x86_64-darwin' }}
